# Generated by Django 4.2.7 on 2024-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_alter_subcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(upload_to='subcategory/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
