# Generated by Django 4.2.7 on 2024-01-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_status'),
        ('subcategory', '0003_alter_subcategory_icon_alter_subcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_subcategory', to='category.category'),
        ),
    ]
