# Generated by Django 4.2.7 on 2024-02-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=33, null=True)),
                ('subject', models.CharField(blank=True, max_length=33, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
