# Generated by Django 4.2.7 on 2024-02-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
