# Generated by Django 4.2.7 on 2024-02-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_wishlistitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
    ]
